image: gcc:latest

stages:
  - build
  - test

variables:
  CC: gcc
  CFLAGS: -g
  AUTOTEST_GIT: "https://moule.informatique.univ-paris-diderot.fr/geoffroy/sy5-2024-2025-projet-fsh-autotests.git"

before_script:
  - apt-get update && apt-get install -y libreadline-dev
  - mkdir -p build

build:
  stage: build
  script:
    - make
  artifacts:
    paths:
      - fsh
    expire_in: 1 hour

test:
  stage: test
  script:
    - echo "Cloning autotests repo..."
    - >-
      if [ ! -d "$AUTOTEST_DIR" ]; then
        if ! git clone "$AUTOTEST_GIT" "$AUTOTEST_DIR"; then
          echo "Failed to clone test repo" >&2;
        fi;
      fi
    - cd "$AUTOTEST_DIR"
    - ./autotests.sh

  dependencies:
    - build